version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'

  app:
    build: .
    image: 'friendsapi'
    container_name: 'app'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'

